name: Build & Test

on:
  push:
    branches: "**"
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - name: setup test project
        run: pnpm i
      - name: build test project
        run: pnpm build
      - name: lint
        run: pnpm lint
      - name: test
        run: pnpm test:ci
      - name: test docker-entrypoint.sh patching
        run: ./scripts/test-docker-entrypoint.sh
      - name: build docker image
        run: pnpm docker:build
      - name: verify container
        run: pnpm docker:verify
      - name: verify container on different base url
        run: pnpm docker:verify-with-overwrites
        
      
